# Generated by Django 4.2 on 2023-04-19 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='code',
            field=models.ImageField(blank=True, upload_to='qr_code', verbose_name='qr'),
        ),
    ]
