# Generated by Django 4.2 on 2023-04-19 15:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий к заказу')),
                ('start_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='начало аренды')),
                ('expired_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='конец аренды')),
                ('paid', models.BooleanField(default=False, verbose_name='Оплачен')),
            ],
            options={
                'verbose_name': 'договор аренды',
                'verbose_name_plural': 'договора аренды',
                'ordering': ['-expired_at'],
            },
        ),
        migrations.AlterField(
            model_name='box',
            name='image',
            field=models.ImageField(blank=True, upload_to='images', verbose_name='Изображение боксов'),
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.AddField(
            model_name='rental',
            name='box',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rents', to='storage.box', verbose_name='аренда'),
        ),
        migrations.AddField(
            model_name='rental',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rents', to=settings.AUTH_USER_MODEL, verbose_name='аренда'),
        ),
    ]
