# Generated by Django 4.2 on 2023-04-19 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0003_alter_rental_expired_at_alter_rental_start_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rental',
            old_name='start_at',
            new_name='started_at',
        ),
    ]
