# Generated by Django 4.2 on 2023-04-24 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0005_order_box_alter_order_amount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'счет', 'verbose_name_plural': 'счета'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'клиент', 'verbose_name_plural': 'клиенты'},
        ),
        migrations.AddField(
            model_name='order',
            name='payment_id',
            field=models.CharField(default='0', max_length=36),
        ),
    ]
